EMP_SAL_CALCULATOR/EMP_SAL_CALCULATOR/Models/ErrorViewModel.cs
namespace EMP_SAL_CALCULATOR.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EMP_SAL_CALCULATOR/EMP_SAL_CALCULATOR/Models/SalDet.cs
namespace EMP_SAL_CALCULATOR.Models
{
    public class SalDet
    {
        public string? EmpName { get; set; }
        public float Salary { get; set; }
        public float Tax { get; set; }
        public float AccSalary { get; set; }

    }
}

EMP_SAL_CALCULATOR/EMP_SAL_CALCULATOR/Controllers/HomeController.cs
using EMP_SAL_CALCULATOR.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EMP_SAL_CALCULATOR.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EMP_SAL_CALCULATOR/EMP_SAL_CALCULATOR/Controllers/SalaryController.cs
using EMP_SAL_CALCULATOR.Models;
using Microsoft.AspNetCore.Mvc;

namespace EMP_SAL_CALCULATOR.Controllers
{
    public class SalaryController : Controller
    {
        public IActionResult Index()
        {
            return View(new SalDet());
        }

        
        [HttpPost]
        public ActionResult Index(SalDet s)
        {
            if (s.Salary > 100000)
            {
                s.Tax = s.Salary * 20 / 100;
            }
            else if(s.Salary > 80000)
            {
                s.Tax = s.Salary * 10 / 100;
            }
            else if (s.Salary > 60000)
            {
                s.Tax = s.Salary * 5 / 100;
            }
            else
            {
                s.Tax = 0;
            }

            s.AccSalary = s.Salary - s.Tax;
            return View(s);
        }
    }
}

EMP_SAL_CALCULATOR/EMP_SAL_CALCULATOR/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

EMP_SAL_CALCULATOR/EMP_SAL_CALCULATOR/Views/Salary/Index.cshtml
@model EMP_SAL_CALCULATOR.Models.SalDet


@{
	ViewBag.Title="Index";
}

<html>
	<head>

	</head>
	<body>
		<h1>SALARY CALCULATOR</h1>
		<div class="row">
			@using(Html.BeginForm("/Index","Salary",FormMethod.Post))
			{
				<div class="form-group">
					<lable for="name">Employee Name</lable>
				<input type="text" class="form-control" id="EmpName" name="EmpName" value="@Model.EmpName" />
				</div>
				<br/>
				<div class="form-group">
					<lable for="name">Base Salary</lable>
				<input type="text" class="form-control" id="Salary" name="Salary" value="@Model.Salary" />
				</div>
				<br/>
				<div class="form-group">
					<lable for="name">Tax</lable>
				<input type="text" class="form-control" id="Tax" name="Tax" value="@Model.Tax" />
				</div>
				<br/>
				<div class="form-group">
					<lable for="name">Acctual Salary</lable>
				<input type="text" class="form-control" id="AccSalary" name="AccSalary" value="@Model.AccSalary" />
				</div>
				<br/>
				<button type="submit" class="btn btn-info" id="add" value="add">Calculate</button>

			}

		</div>
	</body>
</html>

EMP_SAL_CALCULATOR/EMP_SAL_CALCULATOR/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EMP_SAL_CALCULATOR</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EMP_SAL_CALCULATOR.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EMP_SAL_CALCULATOR</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - EMP_SAL_CALCULATOR - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>